version: '2'

services:
  web:
    image: nginx
    container_name: iteastyle-web-test
    restart: always
    volumes:
     - /root/service/iteastyle-web-test:/usr/share/nginx/html:ro
    expose:
     - "443"
    environment:
<<<<<<< HEAD
      VIRTUAL_HOST: iteastyle.aimeow.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: iteastyle.aimeow.com
=======
      VIRTUAL_HOST: iteastyle.cn,www.iteastyle.cn
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: iteastyle.cn,www.iteastyle.cn
>>>>>>> master
      LETSENCRYPT_EMAIL: a18814888787@gmail.com

networks:
  default:
    external:
      name: nginx-proxy