version: '2'

services:
  web:
    image: nginx
    container_name: iteastyle_web
    restart: always
    volumes:
     - /root/service/iteastyle-web:/usr/share/nginx/html:ro
    expose:
     - "443"
    environment:
      VIRTUAL_HOST: iteastyle.cn
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: iteastyle.cn
      LETSENCRYPT_EMAIL: a18814888787@gmail.com

networks:
  default:
    external:
      name: nginx-proxy